"""Extract every display equation from the paper into a standalone .tex file.

Generates ``equations.tex`` from the paper's Quarto sources: all display math
blocks (``$$ ... $$``, labeled or not) from every section included by
``paper/index.qmd``, each with its section heading, the prose paragraph that
introduces it, and the immediate trailing explanation ("where ..." lines).
Labeled equations carry their Quarto label (e.g. ``eq-trigger-phi``) as a tag,
matching the labels referenced in the Lean formalization (``lean/``).

Run from the repository root:

    uv run python submission/replication/extract_equations.py

The output is deterministic and should be regenerated (never hand-edited)
whenever the paper's equations change.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PAPER = REPO / "paper"
OUT = Path(__file__).with_name("equations.tex")

PREAMBLE = r"""% equations.tex — auto-generated by extract_equations.py; do not edit.
%
% Every display equation of "Capacity, Training, and Default in the Race to
% Artificial General Intelligence"
% (main text and Internet Appendix), with its introducing prose and its
% Quarto label (shown as [eq-...] next to the equation). The labels match
% those referenced in the Lean 4 formalization's module docstrings and in
% lean/README.md, so this file is the reference against which the Lean
% package can be checked for faithfulness.
\documentclass[11pt]{article}
\usepackage{amsmath,amssymb}
\usepackage[margin=1in]{geometry}
\usepackage[hidelinks]{hyperref}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt}
\title{Capacity, Training, and Default in the Race to Artificial General
Intelligence:\\ complete equation listing}
\author{Auto-generated from the paper's Quarto sources}
\date{}
\begin{document}
\maketitle
\noindent\emph{Each display equation from the paper and the Internet Appendix
appears below in source order, preceded by the sentence(s) that introduce it
and followed by the immediate explanation of its symbols. Bracketed monospace
tags (e.g.\ {[\texttt{eq-trigger-phi}]}) are the paper's equation labels; the
Lean formalization references these labels. Cross-references and citation keys
from the manuscript are kept as monospace tokens.}
\bigskip
"""

POSTAMBLE = "\\end{document}\n"

HEADING_CMD = {1: "section", 2: "section", 3: "subsection", 4: "subsubsection"}


def strip_footnotes(text: str) -> str:
    """Remove Quarto inline footnotes ``^[...]`` (brackets may nest)."""
    out, i = [], 0
    while i < len(text):
        if text.startswith("^[", i):
            depth, i = 1, i + 2
            while i < len(text) and depth:
                depth += {"[": 1, "]": -1}.get(text[i], 0)
                i += 1
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def prose_to_latex(text: str) -> str:
    """Light markdown-to-LaTeX conversion for prose outside math."""
    text = strip_footnotes(text)
    # crossrefs and citations -> monospace tokens ([-@x], [@x; @y], @x)
    text = re.sub(r"\[-?@([^\]]+)\]", lambda m: r"(\texttt{" + m.group(1) + "})", text)
    text = re.sub(r"@([A-Za-z][A-Za-z0-9_.-]*)", r"\\texttt{\1}", text)
    # bold/italic (applied outside math below)
    parts = text.split("$")
    for j in range(0, len(parts), 2):  # even indices are outside inline math
        p = parts[j]
        p = re.sub(r"\*\*([^*]+)\*\*", r"\\textbf{\1}", p)
        p = re.sub(r"\*([^*]+)\*", r"\\emph{\1}", p)
        for ch in "&%#_":
            p = p.replace(ch, "\\" + ch)
        parts[j] = p
    return "$".join(parts)


def heading_to_latex(line: str) -> str:
    m = re.match(r"^(#{1,4})\s+(.*)$", line)
    if m is None:  # unreachable: callers match the same pattern first
        raise ValueError(line)
    level, title = len(m.group(1)), m.group(2)
    title = re.sub(r"\s*\{.*\}\s*$", "", title)  # drop {#sec-...} attributes
    return f"\\{HEADING_CMD[level]}*{{{prose_to_latex(title)}}}"


def include_order() -> list[Path]:
    order = []
    for m in re.finditer(
        r"\{\{<\s*include\s+(\S+)\s*>\}\}", (PAPER / "index.qmd").read_text()
    ):
        order.append(PAPER / m.group(1))
    return order


def is_skippable(line: str) -> bool:
    s = line.strip()
    return s.startswith("|") or s.startswith(":::") or s.startswith(": ")


def extract_file(path: Path) -> list[dict]:
    """Return a list of items: {'kind': 'heading'|'equation', ...}."""
    lines = path.read_text().splitlines()
    items, para, i, in_code = [], [], 0, False
    while i < len(lines):
        line = lines[i]
        if line.strip().startswith("```"):
            in_code = not in_code
            i += 1
            continue
        if in_code or is_skippable(line):
            i += 1
            continue
        if re.match(r"^#{1,4}\s", line):
            items.append({"kind": "heading", "tex": heading_to_latex(line)})
            para = []
            i += 1
            continue
        if line.strip() == "$$":  # opening fence
            body = []
            i += 1
            label = None
            while i < len(lines):
                m = re.match(
                    r"^\$\$\s*(?:\{#(eq-[A-Za-z0-9-]+)\})?\s*$", lines[i].strip()
                )
                if m:
                    label = m.group(1)
                    i += 1
                    break
                body.append(lines[i].strip())
                i += 1
            # trailing explanation: contiguous prose right after the fence,
            # unless that run introduces the next equation (then it belongs
            # to the next equation's pre-context)
            post, j = [], i
            while (
                j < len(lines)
                and lines[j].strip()
                and lines[j].strip() != "$$"
                and not re.match(r"^#{1,4}\s", lines[j])
                and not is_skippable(lines[j])
            ):
                post.append(lines[j])
                j += 1
            if j < len(lines) and lines[j].strip() == "$$":
                post = []  # leave for the next equation's pre-context
            else:
                i = j
            items.append({
                "kind": "equation",
                "pre": " ".join(para).strip(),
                "body": "\n".join(body).rstrip(),
                "label": label,
                "post": " ".join(post).strip(),
            })
            para = []
            continue
        para = [*para, line.strip()] if line.strip() else []
        i += 1
    return items


def render(items: list[dict]) -> str:
    out = []
    for it in items:
        if it["kind"] == "heading":
            out.append(it["tex"] + "\n")
            continue
        if it["pre"]:
            out.append(prose_to_latex(it["pre"]) + "\n")
        tag = f"\\tag*{{[\\texttt{{{it['label']}}}]}}\n" if it["label"] else ""
        out.append(f"\\begin{{equation*}}\n{tag}{it['body']}\n\\end{{equation*}}\n")
        if it["post"]:
            out.append(prose_to_latex(it["post"]) + "\n")
        out.append("\n")
    return "\n".join(out)


def main() -> None:
    chunks, n_eq, n_lab = [PREAMBLE], 0, 0
    for path in include_order():
        items = extract_file(path)
        eqs = [x for x in items if x["kind"] == "equation"]
        if not eqs:
            continue
        n_eq += len(eqs)
        n_lab += sum(1 for x in eqs if x["label"])
        # keep only headings that precede at least one equation downstream
        pruned, pending = [], []
        for x in items:
            if x["kind"] == "heading":
                pending.append(x)
            else:
                pruned.extend(pending)
                pending = []
                pruned.append(x)
        chunks.append(render(pruned))
    chunks.append(POSTAMBLE)
    OUT.write_text("\n".join(chunks))
    print(f"wrote {OUT.relative_to(REPO)}: {n_eq} equations ({n_lab} labeled)")


if __name__ == "__main__":
    main()
